language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  - COVERAGE_FILE="$TRAVIS_BUILD_DIR/coverage/coverage.xml"

before_install:
  - bash travis/setup_creds.sh
  - mkdir "$TRAVIS_BUILD_DIR/coverage"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - source ./setup_env.sh

script:
  - pytest --cov=src --cov-report xml:$COVERAGE_FILE tests/
  - cwltest --basedir cwl_test_dir --test tests/cwl/test_megahit.yml --tool cwltool
  - cwltest --basedir cwl_test_dir --test tests/cwl/test_metaspades.yml --tool cwltool

after_script:
  - python-codacy-coverage -r $COVERAGE_FILE