language: python
python:
  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"
#  - "3.7-dev"
sudo: required

services:
  - docker

env:
  - COVERAGE_FILE="$TRAVIS_BUILD_DIR/coverage/coverage.xml" BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

before_install:
  - bash travis/setup_creds.sh
  - mkdir "$TRAVIS_BUILD_DIR/coverage"

install:
  - docker build -t "migueldboland/cwl-assembly-readfq" $TRAVIS_BUILD_DIR/cwl/stats/readfq/
  - docker build -t "migueldboland/cwl-assembly-stats-report" $TRAVIS_BUILD_DIR/cwl/stats/stats_report/
  - docker build -t "migueldboland/cwl-assembly-fasta-trimming" $TRAVIS_BUILD_DIR/cwl/stats/fasta_trimming/

  - source ./setup_env.sh
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

script:
# Package installation
  - pip install git+https://github.com/EBI-Metagenomics/CWL-assembly.git@$BRANCH
  - pip install git+https://github.com/DataBiosphere/toil.git
  - assembly_cli megahit -s SRP074153 -r SRR6257420 -d $TRAVIS_BUILD_DIR/tests/assembly_dir --docker-cmd udocker -m 5 -c 1

  - pytest --cov=src --cov-report xml:$COVERAGE_FILE tests/

#  CWL Tests
#  Assemblers
  - cwltest --basedir cwl_test_dir --test tests/cwl/tools/assemblers/test_megahit.yml --tool cwltool --verbose 
  - cwltest --basedir cwl_test_dir --test tests/cwl/tools/assemblers/test_metaspades.yml --tool cwltool --verbose 
  - cwltest --basedir cwl_test_dir --test tests/cwl/tools/assemblers/test_spades.yml --tool cwltool --verbose 

# Stats tools
  - cwltest --basedir cwl_test_dir --test tests/cwl/tools/stats/test_readfq.yml --tool cwltool --verbose 
  - cwltest --basedir cwl_test_dir --test tests/cwl/tools/stats/test_trim_fasta.yml --tool cwltool --verbose 
  - cwltest --basedir cwl_test_dir --test tests/cwl/tools/stats/test_stats_report.yml --tool cwltool --verbose 

# Stats workflows
  - cwltest --basedir cwl_test_dir --test tests/cwl/workflows/test_stats.yml --tool cwltool --verbose

after_script:
  - python-codacy-coverage -r $COVERAGE_FILE