FROM python:3.6-slim
MAINTAINER Miguel Boland <mdb@ebi.ac.uk>

##############################################################
# Dockerfile Version:   18.06.0-ce
# Software:             coverage_report.py
# Software Version:     1.0.0
# Description:          Calculate report and output directory
##############################################################
COPY coverage_report.py /

CMD ["python", "/coverage_report.py"]

