FROM python:3.6-slim

LABEL maintainer="Miguel Boland <mdb@ebi.ac.uk>"

##############################################################
# Dockerfile Version:   18.06.0-ce
# Software:             trim_fasta.py
# Software Version:     1.0.0
# Description:          Calculate report and output directory
##############################################################
COPY . /

CMD ["python", "/trim_fasta.py"]

